In [2]:
import numpy as np
import scipy.io as scio    
import os,re
from PIL import Image
from scipy import ndimage
from matplotlib import pyplot as plt

In [60]:
import cv2

In [24]:
def atoi(text) : 
    return int(text) if text.isdigit() else text

In [25]:
def natural_keys(text) :
    return [atoi(c) for c in re.split('(\d+)', text)]

In [31]:
def resize_images(path,new_path):
    filenames = []
    for root, dirnames, filenames in os.walk(path):
        filenames.sort(key = natural_keys)
        rootpath = root
    #print(filenames)
    print(len(filenames))
    for item in filenames:
        if os.path.isfile(path+item):
            im = Image.open(path+item)
            f, e = os.path.splitext(item)
            imResize = im.resize((128,128), Image.ANTIALIAS)
            #print(new_path +f+ '_resized.jpg')
            imResize.save(new_path+f+'_resized.jpg', 'JPEG', quality=90)

In [32]:
resize_images("/media/prajwala/40267F2A267F2058/Computer Engg/8th sem/Artificial Intelligence/cancer-prediction/melanoma/",
             "/media/prajwala/40267F2A267F2058/Computer Engg/8th sem/Artificial Intelligence/cancer-prediction/melanoma_resized/")

374


In [33]:
resize_images("/media/prajwala/40267F2A267F2058/Computer Engg/8th sem/Artificial Intelligence/cancer-prediction/others/",
             "/media/prajwala/40267F2A267F2058/Computer Engg/8th sem/Artificial Intelligence/cancer-prediction/others_resized/")

1626


In [34]:
resize_images("/media/prajwala/40267F2A267F2058/Computer Engg/8th sem/Artificial Intelligence/cancer-prediction/gt/",
             "/media/prajwala/40267F2A267F2058/Computer Engg/8th sem/Artificial Intelligence/cancer-prediction/gt_resized/")

2000


In [35]:
def get_filenames(path):
    filenames = []
    for root, dirnames, filenames in os.walk(path):
        filenames.sort(key = natural_keys)
        rootpath = root
    print(len(filenames))
    return filenames

In [36]:
root_path = "/media/prajwala/40267F2A267F2058/Computer Engg/8th sem/Artificial Intelligence/cancer-prediction/"

In [37]:
filenames_melanoma = get_filenames(root_path+"melanoma_resized/")
filenames_others = get_filenames(root_path+"others_resized/")

374
1626


In [38]:
filenames_gt = get_filenames(root_path+"gt_resized/")

2000


In [39]:
filenames_total = filenames_melanoma+filenames_others
filenames_total.sort(key = natural_keys)

In [40]:
print(filenames_total)
print(len(filenames_total))

['ISIC_0000000_resized.jpg', 'ISIC_0000001_resized.jpg', 'ISIC_0000002_resized.jpg', 'ISIC_0000003_resized.jpg', 'ISIC_0000004_resized.jpg', 'ISIC_0000006_resized.jpg', 'ISIC_0000007_resized.jpg', 'ISIC_0000008_resized.jpg', 'ISIC_0000009_resized.jpg', 'ISIC_0000010_resized.jpg', 'ISIC_0000011_resized.jpg', 'ISIC_0000012_resized.jpg', 'ISIC_0000013_resized.jpg', 'ISIC_0000014_resized.jpg', 'ISIC_0000015_resized.jpg', 'ISIC_0000016_resized.jpg', 'ISIC_0000017_resized.jpg', 'ISIC_0000018_resized.jpg', 'ISIC_0000019_resized.jpg', 'ISIC_0000020_resized.jpg', 'ISIC_0000021_resized.jpg', 'ISIC_0000022_resized.jpg', 'ISIC_0000023_resized.jpg', 'ISIC_0000024_resized.jpg', 'ISIC_0000025_resized.jpg', 'ISIC_0000026_resized.jpg', 'ISIC_0000027_resized.jpg', 'ISIC_0000028_resized.jpg', 'ISIC_0000029_resized.jpg', 'ISIC_0000030_resized.jpg', 'ISIC_0000031_resized.jpg', 'ISIC_0000032_resized.jpg', 'ISIC_0000034_resized.jpg', 'ISIC_0000035_resized.jpg', 'ISIC_0000036_resized.jpg', 'ISIC_0000037_resiz

In [59]:
print(filenames_gt)

['ISIC_0000000_segmentation_resized.jpg', 'ISIC_0000001_segmentation_resized.jpg', 'ISIC_0000002_segmentation_resized.jpg', 'ISIC_0000003_segmentation_resized.jpg', 'ISIC_0000004_segmentation_resized.jpg', 'ISIC_0000006_segmentation_resized.jpg', 'ISIC_0000007_segmentation_resized.jpg', 'ISIC_0000008_segmentation_resized.jpg', 'ISIC_0000009_segmentation_resized.jpg', 'ISIC_0000010_segmentation_resized.jpg', 'ISIC_0000011_segmentation_resized.jpg', 'ISIC_0000012_segmentation_resized.jpg', 'ISIC_0000013_segmentation_resized.jpg', 'ISIC_0000014_segmentation_resized.jpg', 'ISIC_0000015_segmentation_resized.jpg', 'ISIC_0000016_segmentation_resized.jpg', 'ISIC_0000017_segmentation_resized.jpg', 'ISIC_0000018_segmentation_resized.jpg', 'ISIC_0000019_segmentation_resized.jpg', 'ISIC_0000020_segmentation_resized.jpg', 'ISIC_0000021_segmentation_resized.jpg', 'ISIC_0000022_segmentation_resized.jpg', 'ISIC_0000023_segmentation_resized.jpg', 'ISIC_0000024_segmentation_resized.jpg', 'ISIC_0000025_s

In [45]:
total_images = []
for file in filenames_total:
    if os.path.exists(root_path+"melanoma_resized/"+file):
        total_images.append(ndimage.imread(root_path+"melanoma_resized/"+file))
    else:
        total_images.append(ndimage.imread(root_path+"others_resized/"+file))

In [46]:
len(total_images)

2000

In [47]:
total_images = np.array(total_images)

In [48]:
np.save('total_images.npy',total_images)

In [52]:
gt_images = []
for file in filenames_gt:
    gt_images.append(ndimage.imread(root_path+"gt_resized/"+file))

In [55]:
gt_images = np.array(gt_images)

In [1]:
plt.imshow(gt_images[0], cmap = "gray")
plt.show()

NameError: name 'plt' is not defined

In [58]:
np.unique(gt_images[0])

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  35,  36,  37,  39,  40,  41,  42,
        43,  44,  46,  47,  48,  49,  50,  51,  53,  54,  55,  56,  57,
        59,  61,  62,  63,  64,  65,  66,  67,  68,  69,  71,  74,  75,
        77,  79,  80,  81,  83,  84,  85,  86,  87,  88,  91,  92,  94,
        95,  97,  98,  99, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 118, 119, 120, 121, 122, 123, 125, 127,
       132, 133, 134, 135, 136, 137, 138, 139, 141, 142, 143, 145, 146,
       147, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 161,
       164, 167, 168, 169, 171, 173, 174, 176, 177, 178, 179, 181, 182,
       183, 184, 185, 186, 187, 188, 189, 190, 192, 193, 194, 195, 197,
       198, 200, 201, 202, 205, 206, 207, 208, 209, 212, 213, 214, 216,
       217, 219, 220, 222, 224, 225, 226, 227, 228, 229, 230, 23

In [61]:
gt_labels_binary = []

In [62]:
for gt_image in gt_images:
    ret,image = cv2.threshold(gt_image,127,255,cv2.THRESH_BINARY)
    gt_labels_binary.append(image)

In [63]:
gt_labels_binary=np.array(gt_labels_binary)

In [65]:
np.unique(gt_labels_binary[0])

array([  0, 255], dtype=uint8)

In [66]:
gt_labels_binary/=255

In [67]:
np.unique(gt_labels_binary[0])

array([0, 1], dtype=uint8)

In [68]:
np.save('gt_labels_binary.npy',gt_labels_binary)